apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-model-cache
  namespace: hawk
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi